<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <MrbrSourceGeneratorProject>..\..\Mrbr.Encryption.Data\Mrbr.Encryption.Data.SourceGenerator\Mrbr.Encryption.Data.SourceGenerator.csproj</MrbrSourceGeneratorProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mrbr.Encryption.Data.Identity\Mrbr.Encryption.Data.Identity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Mrbr.Encryption.Data.SourceGenerator" Version="2.0.0" Condition="!Exists('$(MrbrSourceGeneratorProject)')" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="$(MrbrSourceGeneratorProject)" Condition="Exists('$(MrbrSourceGeneratorProject)')" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
